openapi: 3.1.0
info:
  title: Physical AI Textbook Platform API
  version: 1.0.0
  description: |
    FastAPI backend for AI-Native Physical AI & Humanoid Robotics Textbook Platform.

    **Features**:
    - RAG Chatbot with dynamic skill loading (Matrix Protocol)
    - Content personalization based on hardware profile
    - Urdu translation with code preservation
    - Better-Auth authentication (Email/GitHub OAuth)

    **Constitution Compliance**: Adheres to Article II (Authorized Tech Stack) and Article VI (Engineering Standards)

  contact:
    name: AI-Native Institute
    url: https://github.com/RameezBadruddinKhwaja/GIAIC-Hackathon1-Quater4

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api-physical-ai-textbook.onrender.com
    description: Production server (Render deployment)

tags:
  - name: Authentication
    description: Better-Auth endpoints for user signup/signin and onboarding
  - name: RAG Chatbot
    description: Vector search + OpenAI Agents SDK for Q&A
  - name: Personalization
    description: Hardware-aware content adaptation
  - name: Localization
    description: Urdu translation with code preservation
  - name: Health
    description: System health checks

paths:
  # ==================== Authentication Endpoints ====================

  /api/auth/signup:
    post:
      tags:
        - Authentication
      summary: User signup (email/password)
      description: |
        Creates a new user account with email/password authentication (FR-012).
        Triggers onboarding flow after successful signup.
      operationId: auth_signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: learner@example.com
                password:
                  type: string
                  format: password
                  minLength: 8
                  example: SecurePass123!
              required:
                - email
                - password
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    format: uuid
                    example: 550e8400-e29b-41d4-a716-446655440000
                  jwt_token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  onboarding_required:
                    type: boolean
                    example: true
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          description: Email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/auth/signin:
    post:
      tags:
        - Authentication
      summary: User signin (email/password or GitHub OAuth)
      description: |
        Authenticates user and returns JWT token (FR-012).
        Supports both email/password and GitHub OAuth flows.
      operationId: auth_signin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                      format: password
                  required:
                    - email
                    - password
                - type: object
                  properties:
                    github_code:
                      type: string
                      description: GitHub OAuth authorization code
                  required:
                    - github_code
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    format: uuid
                  jwt_token:
                    type: string
                  user_profile:
                    $ref: '#/components/schemas/UserProfile'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/auth/onboarding:
    post:
      tags:
        - Authentication
      summary: Complete user onboarding questionnaire
      description: |
        Stores user hardware profile and programming language preference (FR-013).
        Questions: "Do you own an NVIDIA RTX GPU?" and "Are you a Python or C++ developer?"
      operationId: auth_onboarding
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                hardware_profile:
                  type: string
                  enum: [rtx_4090, jetson_orin_nano]
                  example: rtx_4090
                programming_language:
                  type: string
                  enum: [python, cpp]
                  example: python
              required:
                - hardware_profile
                - programming_language
      responses:
        '200':
          description: Onboarding completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Onboarding completed successfully
                  user_profile:
                    $ref: '#/components/schemas/UserProfile'
        '401':
          $ref: '#/components/responses/Unauthorized'

  # ==================== RAG Chatbot Endpoints ====================

  /api/chat:
    post:
      tags:
        - RAG Chatbot
      summary: Ask chatbot a question about course content
      description: |
        RAG pipeline: Query embedding → Qdrant search → OpenAI Agents SDK → Response with citations (FR-007, FR-008, FR-009).
        Supports Matrix Protocol dynamic skill loading (FR-027, FR-028).
      operationId: chat_query
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  minLength: 3
                  maxLength: 500
                  example: What are ROS 2 Topics and how do they work?
                hardware_context:
                  type: string
                  enum: [rtx_4090, jetson_orin_nano, both]
                  description: Filter results by hardware relevance
                  example: both
              required:
                - query
      responses:
        '200':
          description: Chatbot response with citations
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    example: ROS 2 Topics are named buses for message passing between nodes...
                  citations:
                    type: array
                    items:
                      $ref: '#/components/schemas/Citation'
                  skills_loaded:
                    type: array
                    items:
                      type: string
                    example: [ros2-mastery, edge-computing]
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/RateLimitExceeded'

  # ==================== Personalization Endpoints ====================

  /api/personalize:
    post:
      tags:
        - Personalization
      summary: Personalize chapter content for user hardware
      description: |
        Rewrites code blocks based on user's hardware profile (FR-015, FR-016, FR-018, FR-019).
        Uses GPT-4 for content adaptation with 7-day caching.
      operationId: personalize_chapter
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chapter_id:
                  type: string
                  pattern: ^week-\d{2}-[a-z0-9-]+$
                  example: week-08-isaac-sim-basics
              required:
                - chapter_id
      responses:
        '200':
          description: Personalized content returned (cache hit or freshly generated)
          content:
            application/json:
              schema:
                type: object
                properties:
                  personalized_mdx:
                    type: string
                    description: Hardware-optimized MDX content
                  hardware_profile:
                    type: string
                    enum: [rtx_4090, jetson_orin_nano]
                  cache_hit:
                    type: boolean
                    description: Whether content was served from cache
                  generated_at:
                    type: string
                    format: date-time
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Chapter not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Personalization service unavailable (OpenAI API error)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  # ==================== Localization Endpoints ====================

  /api/translate:
    post:
      tags:
        - Localization
      summary: Translate chapter content to Urdu
      description: |
        Translates prose to Roman/Formal Urdu while preserving code blocks (FR-019, FR-020, FR-023, FR-024).
        Uses GPT-4 for translation with 7-day caching.
      operationId: translate_chapter
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chapter_id:
                  type: string
                  pattern: ^week-\d{2}-[a-z0-9-]+$
                  example: week-01-ros2-basics
                target_language:
                  type: string
                  enum: [roman_urdu, formal_urdu]
                  example: roman_urdu
              required:
                - chapter_id
                - target_language
      responses:
        '200':
          description: Translated content returned (cache hit or freshly generated)
          content:
            application/json:
              schema:
                type: object
                properties:
                  translated_mdx:
                    type: string
                    description: Urdu-translated MDX (code blocks preserved in English)
                  target_language:
                    type: string
                    enum: [roman_urdu, formal_urdu]
                  cache_hit:
                    type: boolean
                  generated_at:
                    type: string
                    format: date-time
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Chapter not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Translation service unavailable (OpenAI API error)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  # ==================== Health Check Endpoints ====================

  /api/health:
    get:
      tags:
        - Health
      summary: System health check
      description: |
        Returns health status of all dependencies (Neon, Qdrant, OpenAI, Better-Auth).
      operationId: health_check
      responses:
        '200':
          description: System healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  services:
                    type: object
                    properties:
                      neon_db:
                        type: string
                        example: connected
                      qdrant_cloud:
                        type: string
                        example: connected
                      openai_api:
                        type: string
                        example: available
                      better_auth:
                        type: string
                        example: operational
        '503':
          description: System unhealthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: unhealthy
                  services:
                    type: object
                    additionalProperties:
                      type: string

# ==================== Components ====================

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from /api/auth/signin

  schemas:
    UserProfile:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        auth_provider:
          type: string
          enum: [email, github]
        hardware_profile:
          type: string
          enum: [rtx_4090, jetson_orin_nano]
          nullable: true
        programming_language:
          type: string
          enum: [python, cpp]
          nullable: true
        created_at:
          type: string
          format: date-time
        last_login:
          type: string
          format: date-time
          nullable: true

    Citation:
      type: object
      properties:
        chapter_id:
          type: string
          example: week-01-ros2-basics
        section_id:
          type: string
          example: nodes-and-topics
        content_snippet:
          type: string
          description: 100-character excerpt from cited content
          example: ROS 2 Nodes are independent processes that perform computation...
        chapter_url:
          type: string
          format: uri
          example: https://textbook.example.com/docs/week-01-ros2-basics#nodes-and-topics

    Error:
      type: object
      properties:
        error:
          type: string
          example: Invalid request parameters
        detail:
          type: string
          example: Field 'query' must be at least 3 characters long
        timestamp:
          type: string
          format: date-time

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Authentication required or JWT token invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    RateLimitExceeded:
      description: Too many requests (rate limit exceeded)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

# ==================== Security Requirements ====================

security:
  - BearerAuth: []
