"""Create database tables

Revision ID: 5a45129dcc34
Revises: 
Create Date: 2025-12-05 22:22:57.119811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a45129dcc34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.Enum('EMAIL', 'GITHUB', name='authprovider'), nullable=False),
    sa.Column('hardware_profile', sa.Enum('RTX_4090', 'JETSON_ORIN_NANO', name='hardwareprofile'), nullable=True),
    sa.Column('programming_language', sa.Enum('PYTHON', 'CPP', name='programminglanguage'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
